CREATE TABLE invoices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(50) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    invoice_description TEXT,
    order_date DATE,
    order_status VARCHAR(50),
    order_id VARCHAR(50),
    billing_address TEXT,
    shipping_address TEXT,
    bank VARCHAR(255),
    account_no VARCHAR(50),
    due_date DATE,
    subtotal DECIMAL(10, 2),
    discount DECIMAL(5, 2),
    total_amount DECIMAL(10, 2),
    notes TEXT,
    item_name VARCHAR(255),
    quantity INT,
    price DECIMAL(10, 2),
    total DECIMAL(10, 2),
    UNIQUE KEY unique_invoice_item (invoice_number, item_name) -- To avoid duplicate entries
);
